services:
  - type: web
    name: tournament-backend
    env: node
    plan: free
    repo: https://github.com/Aman42942/Protocols-Turnaments
    region: singapore # Optional: closer to India
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CASHFREE_APP_ID
        sync: false
      - key: CASHFREE_SECRET_KEY
        sync: false
      - key: CASHFREE_ENV
        default: "PRODUCTION"
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: API_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_CLIENT_ID
        sync: false
      - key: FACEBOOK_CLIENT_SECRET
        sync: false
